@startuml
!pragma useVerticalIf on
start
:Login;
:Access Home/Dashboard;
:Access Assets Register;
:Search for Item;
if (Item Exist?) then (Y)
  :Request Allocation;
  if (Meets Criteria?) then (Y)
    :Create Allocation;
    :Approve Allocation;
    :Update Asset Register;
  else (N)
   :Reject Allocation;
  endif
  :Notify User;
else (N)
  :Place Request;
  if (Valid?) then (Y)
    : Certify Request;
    : Approve Request;
    : Autocreate Order;
   if (Valid?) then (Y)
      :Certify Order;
      :Approve Order;
      :Autocreate Bid;
      :Notify Suppliers;
      :Place Bid;
      if (Valid?) then (Y)
        :Approve Bid;
        :Supply Order;
        if (OK?) then (Y)
          : Receive Items;
          : Update Asset Register;
          : Notify User;           
        else (N)
          :Reject Item;
        endif
      else (N)
      endif
      :Notify Supplier/Bidder;
      if (Order Complete?) then (Y)
      :Create Invoice;
      :Certify Invoice;
      :Approve Invoice;  
      :Create Payment;   
      :Notify Supplier;
      :Supplier Send Receipt;   
      :Upload Receipt;  
      endif
   else (N)
      :Reject Order;
      :Notify User;
   endif
else (N)
  :Reject Request;
  :Notify User;
endif
endif
stop
@enduml
