#version: '3.7'

services:
  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=discovery-service
        - APP_VERSION=1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    expose:
      - 8761
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
#    network_mode: "host"
    networks:
      - eprocure-network
  configurations-service:
    build:
      context: configurations-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=configurations-service
        - APP_VERSION=1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    expose:
      - 8888
    ports:
      - 8888:8888
    depends_on:
      - discovery-service
      - rabbitmq
    networks:
      - eprocure-network
  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=gateway-service
        - APP_VERSION=1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery-service:8761/eureka
         -DCONFIG_SERVER=http://configurations-service:8888
    restart: on-failure
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - discovery-service
      - configurations-service
      - rabbitmq
    networks:
      - eprocure-network
  setups-service:
    build:
      context: setups-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=setups-service
        - APP_VERSION=1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    expose:
      - 8084
    ports:
      - 8084:8084
    depends_on:
      - discovery-service
      - configurations-service
      - gateway-service
      - rabbitmq
      - mysql
    networks:
      - eprocure-network
  workflow-service:
    build:
      context: workflow-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=workflow-service
        - APP_VERSION=1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery-service:8761/eureka
         -DCONFIG_SERVER=http://configurations-service:8888
    restart: on-failure
    expose:
      - 8083
    ports:
      - 8083:8083
    depends_on:
      - discovery-service
      - gateway-service
      - configurations-service
      - rabbitmq
      - mysql
    networks:
      - eprocure-network
  employees-service:
    build:
      context: employees-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=employees-service
        - APP_VERSION=1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq 
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery-service:8761/eureka
         -DCONFIG_SERVER=http://configurations-service:8888
    restart: on-failure
    expose:
      - 8085
    ports:
      - 8085:8085
    depends_on:
      - discovery-service
      - configurations-service
      - gateway-service
      - setups-service
      - workflow-service
      - rabbitmq
      - mysql
    networks:
      - eprocure-network      
  rabbitmq:
    image: rabbitmq:4.1-rc
    container_name: rabbitmq  
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - eprocure-network
  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: e_procure_db
      MYSQL_ROOT_PASSWORD: Root123#@!
      MYSQL_USER: dev
      MYSQL_PASSWORD: Dev123#@!
networks:
  eprocure-network:
    driver: bridge
