version: '3'

services:
  discovery-service:
    image: e-procure/discovery-service:latest
    container_name: discovery-service
    build:
      args:
        - APP_NAME=discovery-service
        - APP_VERSION=1.0.0
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - eprocure-network
  configurations-service:
    image: e-procure/configurations-service:latest
    container_name: configurations-service
    build:
      args:
        - APP_NAME=configurations-service
        - APP_VERSION=1.0.0
    expose:
      - 8888
    ports:
      - 8888:8888
    depends_on:
      - discovery-service
    networks:
      - eprocure-network
  gateway-service:
    image: e-procure/gateway-service:latest
    container_name: gateway-service
    build:
      args:
        - APP_NAME=gateway-service
        - APP_VERSION=1.0.0
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - configurations-service
    networks:
      - eprocure-network
  setups-service:
    image: e-procure/setups-service:latest
    container_name: setups-service
    build:
      args:
        - APP_NAME=setups-service
        - APP_VERSION=1.0.0
    expose:
      - 8084
    ports:
      - 8084:8084
    depends_on:
      - configurations-service
    networks:
      - eprocure-network
  workflow-service:
    image: e-procure/workflow-service:latest
    container_name: workflow-service
    build:
      args:
        - APP_NAME=workflow-service
        - APP_VERSION=1.0.0
    expose:
      - 8083
    ports:
      - 8083:8083
    depends_on:
      - configurations-service
    networks:
      - eprocure-network

networks:
  eprocure-network: