spring:
  application:
    name: workflow-service
  config:
    import: optional:configserver:${CONFIG_SERVER:http://host.docker.internal:8888}
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 5
    url: jdbc:mysql://localhost:3306/eprocure_workflow_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: Dev123#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql