spring:
  application:
    name: discovery-service
server:
  port: 8761 #default port where discovery client is registered
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"