server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: setups
        uri: lb://setups-service
        predicates:
        - Path=/setups/**
        filters:
        - StripPrefix=1
      - id: workflow
        uri: lb://workflow-service
        predicates:
        - Path=/workflow/**
        filters:
        - StripPrefix=1
      - id: inventory
        uri: lb://inventory-service
        predicates:
        - Path=/inventory/**
        filters:
        - StripPrefix=1
      - id: suppliers
        uri: lb://suppliers-service
        predicates:
        - Path=/suppliers/**
      - id: orders
        uri: lb://orders-service
        predicates:
        - Path=/orders
      - id: invoices
        uri: lb://invoices-service
        predicates:
        - Path=/invoices
      - id: payments
        uri: lb://payments-service
        predicates:
        - Path=/payments        
info:
  app:
    name: ${spring.application.name}
eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
management:
  endpoint:
      gateway:
         enabled: true
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info  
          - gateway
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
