spring:
  application:
    name: setups-service
server:
  port: 8084
eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"